// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmrheirhdaowdgvkobtl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcmhlaXJoZGFvd2RndmtvYnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDY3MTEsImV4cCI6MjA2ODY4MjcxMX0.m7UQAYobuYorSHlf2vKDH6iQEDkXkbeVkr0IGGXwE3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});